### ISSUE TITLE
字体页面模糊&撕过的页面touch事件不灵敏

### ISSUE THREAD

**Issue by betseyliu** [Ovilia/2019-typography-calendar#10]
1. 每天的日历页面字体有点模糊，也有可能字体颜色造成的（我自己做项目的时候，灰色就是比黑色显得模糊），我的手机是IPHONE X

2. 看撕下的页面时，想要看压在下面的图片， 但是touch事件不灵敏，无法知道是否选中了这个页面，拖动体验也有些问题

以上~~

**Comment by Ovilia** [comment]
感谢建议~

touch 不灵敏具体表现为什么，是响应比较慢还是什么？我这边 iPhone 7 好像挺正常的。
