### ISSUE TITLE
iPhone 8 两位数的日期右面会有截断

### ISSUE THREAD

**Issue by boltomli** [Ovilia/2019-typography-calendar#18]
是设计本身如此吗？
![1161548292461_ pic](https://user-images.githubusercontent.com/5236916/51647706-d6d15f80-1fb8-11e9-9abe-aa52fb5c4191.jpg)

**Comment by Ovilia** [comment]
是的……这是设计……

**Comment by youxfans** [comment]
That is feature.(;•͈́༚•͈̀)

**Comment by youxfans** [comment]
That is feature.(;•͈́༚•͈̀)
