### ISSUE TITLE
安卓版 v1.3.9 日历更新问题

### ISSUE THREAD

**Issue by thehackercat** [Ovilia/2019-typography-calendar#26]
![image](https://user-images.githubusercontent.com/10649416/63241425-3f01ce80-c286-11e9-94c5-92939fadd297.png)

我是在官网安装的安卓版 v1.3.9, 在更新到 7.1 日时，继续下拉出现了更新提示, 但点击链接后跳转到 ios-update.html 页(http://zhangwenli.com/2019-typography-calendar/update-ios.html?ref=inapp-home-update), 故找不到相应的补丁包

想问下这是预期吗, 或者是我的客户端问题吗

-------------------------------------------------
看起来 v1.3.9 只更新到 7.1 号, bump version 已经到了 v1.3.15 但是似乎官网没有地方下载 1.3.15 apk 版本

**Comment by Ovilia** [comment]
目前安卓版处于停更状态……抱歉

**Comment by thehackercat** [comment]
好的, 我 clone 一份自己 build 吧, thx~

这个 issue 可以 close 了

**Comment by Ovilia** [comment]
@thehackercat 如果 build 出来欢迎 PR…… 我这边安卓编译环境出了点问题……

**Comment by Ovilia** [comment]
哦不行，可能需要我签名，那你编译出来自己用吧……
