### ISSUE TITLE
9.7 字体故事 iPhone X 首次撕下可能显示有问题

### ISSUE THREAD

**Issue by boltomli** [Ovilia/2019-typography-calendar#27]
有朋友反馈的，大概是字体真的太高了……撕下前一天之后7只能看到1，而且左上的字也少了一行。重新打开app就正常了。

**Comment by Ovilia** [comment]
感谢报告，请问屏幕分辨率是多少？

**Comment by boltomli** [comment]
截图再通过微信发出来是 1080x2339，实际上应该是 1125x2436 吧，比例是这样没错。

![21568103640_ pic](https://user-images.githubusercontent.com/5236916/64596858-47fa4180-d3e7-11e9-915e-51600f8b16f2.jpg)

**Comment by Ovilia** [comment]
这个问题跟这一天没有特别的关系，有时候我也会碰到，但是没法稳定复现，暂时只能这样……
