### ISSUE TITLE
设计方向

### ISSUE THREAD

**Issue by hongmaoxiao** [Ovilia/2019-typography-calendar#5]
只是个建议，设计上可以借鉴物种日历，我觉得好看极了：https://www.guokr.com/post/814171/

**Comment by Ovilia** [comment]
谢谢~ 我几年前还用过这个日历~
是挺好看的，但是这次的主题是字体，所以可能没有很多配图。等明年或许我可以画一些内容，做一个别的主题的日历。谢谢建议！
