### ISSUE TITLE
全面屏适配似乎有一些问题

### ISSUE THREAD

**Issue by vkcyan** [Ovilia/2019-typography-calendar#8]
我在掘金看到您的作品,很有心意,下载体验了,发现在全面屏适配上似乎有一些小问题呢,向您反馈一下~~我的是小米8
![screenshot_2019-01-04-13-46-05-668_com zhangwenli](https://user-images.githubusercontent.com/33681955/50675162-36c28f00-1027-11e9-93b9-e1e3fc99e1c1.png)

**Comment by Ovilia** [comment]
已修复
